Fix bug 788004 - No email send after invitation creation if offline cache is enabled  [Exception... "'TypeError: aItem.calendar.canNotify is not a function' when calling method: [calIOperationListener::onOperationComplete]" (regression). r=philipp,a=philipp