Fix bug 788004 - No email send after invitation creation if offline cache is enabled  [Exception... "'TypeError: aItem.calendar.canNotify is not a function' when calling method: [calIOperationListener::onOperationComplete]" (regression). r=philipp,a=philipp,a=philipp
--HG--
extra : transplant_source : %DC%19%A6%07d0%08%BA%E5w%2C_%C3%D5%14%DB%00I%AA%D0