Bug 1235154 - Port Bug 869086 to fix right click urlbar error [TypeError this.parentNode.firstChild.focus is not a function] r=Ratty a=IanN for comm-aurora and comm-beta
References:
Bug 869086 - Make textbox.xml resilient against the changes in bug 653881
Bug 653881 - Fix up our XBL1 shadow tree implementation so that we can reuse it for XBL2

--HG--
extra : transplant_source : w%19z%BD%9Ds%9A%0C%D9%29%18%DB%F3%F9%09f%F5V-%19